sonar.organization=arrase
sonar.projectKey=arrase_ollama-agent
sonar.sources=ollama_agent
sonar.tests=tests
sonar.python.version=3.11, 3.12, 3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.ruff.reportPaths=ruff-report.json
sonar.python.mypy.reportPaths=mypy-report.txt
