sonar.projectKey=ollama-agent
sonar.projectName=ollama-agent
sonar.sources=ollama_agent
sonar.tests=tests
sonar.python.version=3.10,3.11,3.12
sonar.exclusions=**/.venv/**,**/build/**,**/dist/**,**/.ruff_cache/**
